name: Show commit details

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display commit information
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Author: ${{ github.event.head_commit.author.name }}"
          echo "Author email: ${{ github.event.head_commit.author.email }}"
          echo "Timestamp: ${{ github.event.head_commit.timestamp }}"
