name: Genius 多模块项目部署 [CI|CD]

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      env: ${{ steps.extract.outputs.env }}
      module: ${{ steps.extract.outputs.module }}
      version: ${{ steps.extract.outputs.version }}
      skip: ${{steps.extract.outputs.skip}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Auto Label
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"<Auto>"* ]]; then
            echo "Commit message contains <Auto>. Proceeding with the workflow."
          else
            echo "Commit message does not contain <Auto>. Skipping the workflow."
            exit 78 
          fi

      - name: Get Commit Info
        id: extract
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          echo "Commit Message: $commit_message"
          
          env=""
          module=""
          version=""
          skip=""
          
          if [[ "$commit_message" =~ -e:([^\ ]*) ]]; then
          env="${BASH_REMATCH[1]}"
          fi
          
          if [[ "$commit_message" =~ -m:([^\ ]*) ]]; then
          module="${BASH_REMATCH[1]}"
          fi
          
          if [[ "$commit_message" =~ -v:([^\ ]*) ]]; then
          version="${BASH_REMATCH[1]}"
          fi
          
          if [[ "$commit_message" =~ -skip:([^\ ]*) ]]; then
          skip="${BASH_REMATCH[1]}"
          fi
          
          echo "Environment: $env"
          echo "Module: $module"
          echo "Version: $version"
          echo "Skip: $skip"
          
          echo "ENV=$env" >> $GITHUB_ENV
          echo "MODULE=$module" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "SKIP=$skip" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        if: ${{ env.SKIP != 'image'}}
        run: |
          mvn package -Dmaven.test.skip=true

      - name: Build and Push Docker Images
        if: ${{ env.SKIP != 'image'}}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}
        run: |
          echo "Module Name: $MODULE"
          cd $MODULE
          mkdir docker
          cp ./Dockerfile ./docker
          cp ./target/*.jar ./docker
          cd docker
          docker build -t $DOCKER_USERNAME/$MODULE:$VERSION .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/$MODULE:$VERSION

      - name: Choose the Server Host
        if: ${{ env.ENV != ''}}
        run: |
          pwd=""
          host=""
          port=""
          if [ "${{ env.ENV }}" == "prod" ]; then
           pwd="${{ secrets.PROD_PWD }}"
           host="${{ secrets.PROD_ADDRESS }}"
           port="${{ secrets.PROD_PORT }}"
          elif [ "${{ env.ENV }}" == "test" ]; then
           pwd="${{ secrets.TEST_PWD }}"
           host="${{ secrets.TEST_ADDRESS }}"
           port="${{ secrets.TEST_PORT }}"
          else
           echo "Invalid environment"
           exit 1
          fi 
          echo "PWD=$pwd" >> $GITHUB_ENV
          echo "HOST=$host" >> $GITHUB_ENV
          echo "PORT=$port" >> $GITHUB_ENV

      - name: Connect Server
        uses: appleboy/ssh-action@master
        with:
          # 同上述
          host: ${{ env.HOST }}
          username: root
          password: ${{ env.PWD }}
          port: ${{ env.PORT }}
          # ssh进入系统后执行什么样的操作。一般是关闭原有的服务在重启
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.MODULE }}:${{ env.VERSION }}
      
